In [2]:
import numpy as np

In [3]:
# 1
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 2 
arr_odd=arr[arr%2==1]
arr_even=arr[arr%2==0]
print(arr_odd)
print(arr_even)

[1 3 5 7 9]
[0 2 4 6 8]


In [5]:
# 3
arr_update_1=np.array([], dtype=int)
for number in arr:
    if number %2==0:
        arr_update_1=np.append(arr_update_1,[number])
    else:
        arr_update_1=np.append(arr_update_1,[100])
print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]
